[chisel]
src.git = "https://github.com/unlsycn/chisel"
src.branch = "mill-bump-1210"
fetch.github = "unlsycn/chisel"

[zaozi]
src.git = "https://github.com/sequencer/zaozi"
src.branch = "master"
fetch.github = "sequencer/zaozi"
