# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  chisel = {
    pname = "chisel";
    version = "8e6b58bfdb11e542ac5a70b14fbf91e3afbde94a";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "chisel";
      rev = "8e6b58bfdb11e542ac5a70b14fbf91e3afbde94a";
      fetchSubmodules = false;
      sha256 = "sha256-4v3aBJCPl/u4bTxqj9OIgGRcjbKrjCTOGEznJg9Zp4k=";
    };
    date = "2025-02-19";
  };
}
