# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  chisel = {
    pname = "chisel";
    version = "d564445dbcd81c6ac3319ef9442db2d177ae124f";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "chisel";
      rev = "d564445dbcd81c6ac3319ef9442db2d177ae124f";
      fetchSubmodules = false;
      sha256 = "sha256-V8CxQ5VIkk2c+7KlQIcQX6Qe2PbMZI7/q+5e4iDXajI=";
    };
    date = "2024-10-16";
  };
}
