name: Build and Run Simulation
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - labeled
env:
  USER: runner

# Cancel the current workflow when new commit pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:

  build-simulators:
    name: "Build Simulators"
    runs-on: [self-hosted, linux, nixos, BIGRAM]
    strategy:
      fail-fast: false
    defaults:
      run:
        working-directory: ./templates/chisel
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: "Build vcs simulator"
        run: |
          nix build \
            --override-input chisel-nix "github:chipsalliance/chisel-nix/${{ github.head_ref || github.ref_name }}" \
            --impure \
            '.#gcd.vcs'
      - name: "Build vcs simulator with trace"
        run: |
          nix build \
            --override-input chisel-nix "github:chipsalliance/chisel-nix/${{ github.head_ref || github.ref_name }}" \
            --impure \
            '.#gcd.vcs-trace'
      - name: "Build verilator simulator"
        run: |
          nix build \
            --override-input chisel-nix "github:chipsalliance/chisel-nix/${{ github.head_ref || github.ref_name }}" \
            --impure \
            '.#gcd.verilated'
      - name: "Build verilator simulator with trace"
        run: |
          nix build \
            --override-input chisel-nix "github:chipsalliance/chisel-nix/${{ github.head_ref || github.ref_name }}" \
            --impure \
            '.#gcd.verilated-trace'

  run-vcs:
    name: "Run VCS"
    strategy:
      fail-fast: false
    runs-on: [self-hosted, linux, nixos]
    defaults:
      run:
        working-directory: ./templates/chisel
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: "Run VCS"
        run: |
          nix build \
            --override-input chisel-nix "github:chipsalliance/chisel-nix/${{ github.head_ref || github.ref_name }}" \
            --impure \
            -L \
            '.#gcd.vcs.tests.simple-sim' && cat result/urgReport/asserts.txt

  run-verilator:
    name: "Run Verilator"
    strategy:
      fail-fast: false
    runs-on: [self-hosted, linux, nixos]
    defaults:
      run:
        working-directory: ./templates/chisel
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: "Run verilator"
        run: |
          nix run \
            --override-input chisel-nix "github:chipsalliance/chisel-nix/${{ github.head_ref || github.ref_name }}" \
            '.#gcd.verilated'

  run-jg-fpv:
    name: "Run JasperGold FPV"
    strategy:
      fail-fast: false
    runs-on: [self-hosted, linux, nixos]
    defaults:
      run:
        working-directory: ./templates/chisel
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: "Run JasperGold FPV"
        run: |
          nix build \
            --override-input chisel-nix "github:chipsalliance/chisel-nix/${{ github.head_ref || github.ref_name }}" \
            --impure \
            '.#gcd.jg-fpv' \
          && cat result/report.txt && $(exit $(cat result/failed_num))
