# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  chisel = {
    pname = "chisel";
    version = "43bba6029fb9afc4806ae8f8396fada426af2a9b";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "chisel";
      rev = "43bba6029fb9afc4806ae8f8396fada426af2a9b";
      fetchSubmodules = false;
      sha256 = "sha256-/t9FJtoXopVq1q9HqFM04tF73dTIObuR7fqKV39Bpq8=";
    };
    date = "2025-04-20";
  };
  zaozi = {
    pname = "zaozi";
    version = "5770967e3301547c547ed2b7bbc7c181f95524bf";
    src = fetchFromGitHub {
      owner = "sequencer";
      repo = "zaozi";
      rev = "5770967e3301547c547ed2b7bbc7c181f95524bf";
      fetchSubmodules = false;
      sha256 = "sha256-U9wZ3sBJbsdjwfunz7rN3YPDKefvRrkdrKGuAXs6WjQ=";
    };
    date = "2025-04-14";
  };
}
