# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  chisel = {
    pname = "chisel";
    version = "6603b9860ce9eddd0520ad1978137b248fdef01a";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "chisel";
      rev = "6603b9860ce9eddd0520ad1978137b248fdef01a";
      fetchSubmodules = false;
      sha256 = "sha256-xZYUAAQLAPyswRnMkMwpRvaV5flBY7AZYkGG2mwe0Pc=";
    };
    date = "2025-04-18";
  };
  zaozi = {
    pname = "zaozi";
    version = "5770967e3301547c547ed2b7bbc7c181f95524bf";
    src = fetchFromGitHub {
      owner = "sequencer";
      repo = "zaozi";
      rev = "5770967e3301547c547ed2b7bbc7c181f95524bf";
      fetchSubmodules = false;
      sha256 = "sha256-U9wZ3sBJbsdjwfunz7rN3YPDKefvRrkdrKGuAXs6WjQ=";
    };
    date = "2025-04-14";
  };
}
