# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  chisel = {
    pname = "chisel";
    version = "1adb02be15884b939f5153b957a31a1a8c903b5c";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "chisel";
      rev = "1adb02be15884b939f5153b957a31a1a8c903b5c";
      fetchSubmodules = false;
      sha256 = "sha256-bNrKjrku/7ATygN2UmdbQTrietFng4DJsOJPNd5Zqp0=";
    };
    date = "2025-04-15";
  };
  zaozi = {
    pname = "zaozi";
    version = "5770967e3301547c547ed2b7bbc7c181f95524bf";
    src = fetchFromGitHub {
      owner = "sequencer";
      repo = "zaozi";
      rev = "5770967e3301547c547ed2b7bbc7c181f95524bf";
      fetchSubmodules = false;
      sha256 = "sha256-U9wZ3sBJbsdjwfunz7rN3YPDKefvRrkdrKGuAXs6WjQ=";
    };
    date = "2025-04-14";
  };
}
